CREATE DATABASE HUNT_THE_WUMPUS;

CREATE TABLE HUNT_THE_WUMPUS.PLAYERS ( 
    EMAIL VARCHAR(100) NOT NULL, 
    WINS INT NOT NULL DEFAULT 0, 
    LOSES INT NOT NULL DEFAULT 0, 
    LAST_PLAYED_DATE DATE NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (EMAIL(100))
) ENGINE = InnoDB;

CREATE TABLE HUNT_THE_WUMPUS.WUMPUSES ( 
    ROW_NUM INT NOT NULL, 
    COL_NUM INT NOT NULL
) ENGINE = InnoDB;

